In [1]:
load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [2]:
catalog

{'dataset_id_96': "kedro_datasets.pandas.csv_dataset.CSVDataset(filepath=PurePosixPath('/home/tathagat/workspace/projects/MLPE/tathagata-ai-839/tathagata-ai-839/data/hw03/dataset_id_96.csv'), "
                  "protocol='file', load_args={}, save_args={'index': False})",
 'parameters': "kedro.io.memory_dataset.MemoryDataset(data='<dict>')"}

In [3]:
df = catalog.load("dataset_id_96")

                    INFO     Loading data from dataset_id_96 (CSVDataset)...                    ]8;id=168774;file:///home/tathagat/workspace/projects/MLPE/tathagata-ai-839/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=143982;file:///home/tathagat/workspace/projects/MLPE/tathagata-ai-839/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#537\537]8;;\

In [4]:
df.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,y
0,no checking,9,existing paid,business,1449.0,<100,4<=X<7,3,female div/dep/mar,none,...,1611.452410,0.817235,10.038805,0.214687,0.909502,0.817235,0.903880,0.706879,0.118076,True
1,0<=X<200,18,existing paid,business,1941.0,>=1000,1<=X<4,4,male single,none,...,318.556316,0.092401,6.619740,0.092401,0.561974,0.571412,0.038957,0.326547,0.290818,False
2,no checking,12,no credits/all paid,furniture/equipment,2759.0,<100,>=7,2,male single,none,...,189.304901,0.326547,3.908182,0.510563,0.303847,0.303744,0.143172,0.036330,0.399235,False
3,no checking,15,critical/other existing credit,furniture/equipment,1520.0,no known savings,>=7,4,male single,none,...,622.036427,0.303744,2.431722,0.746842,0.854968,0.654680,0.966290,0.643655,0.744267,False
4,0<=X<200,15,existing paid,radio/tv,1444.0,no known savings,<1,4,male single,none,...,777.865805,0.746842,9.549677,0.832003,0.005958,0.533358,0.920828,0.183284,0.986948,True

In [5]:
df.dtypes

checking_status            object
duration                    int64
credit_history             object
purpose                    object
credit_amount             float64
savings_status             object
employment                 object
installment_commitment      int64
personal_status            object
other_parties              object
residence_since             int64
property_magnitude         object
age                         int64
other_payment_plans        object
housing                    object
existing_credits            int64
job                        object
num_dependents              int64
own_telephone              object
foreign_worker             object
health_status              object
X_1                       float64
X_2                       float64
X_3                       float64
X_4                       float64
X_5                       float64
X_6                       float64
X_7                       float64
X_8                       float64
X_9                       float64
X_10                      float64
y                            bool
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   checking_status         100 non-null    object
 1   duration                100 non-null    int64
 2   credit_history          100 non-null    object
 3   purpose                 100 non-null    object
 4   credit_amount           100 non-null    float64
 5   savings_status          100 non-null    object
 6   employment              100 non-null    object
 7   installment_commitment  100 non-null    int64
 8   personal_status         100 non-null    object
 9   other_parties           100 non-null    object
 10  residence_since         100 non-null    int64
 11  property_magnitude      100 non-null    object
 12  age                     100 non-null    int64
 13  other_payment_plans     100 non-null    object
 14  housing                 100 non-null    object
 15  existing_credits        100 non-null    int64
 16  job                     100 non-null    object
 17  num_dependents          100 non-null    int64
 18  own_telephone           100 non-null    object
 19  foreign_worker          100 non-null    object
 20  health_status           100 non-null    object
 21  X_1                     100 non-null    float64
 22  X_2                     100 non-null    float64
 23  X_3                     100 non-null    float64
 24  X_4                     100 non-null    float64
 25  X_5                     100 non-null    float64
 26  X_6                     100 non-null    float64
 27  X_7                     100 non-null    float64
 28  X_8                     100 non-null    float64
 29  X_9                     100 non-null    float64
 30  X_10                    100 non-null    float64
 31  y                       100 non-null    bool
dtypes: bool(1), float64(11), int64(6), object(14)
memory usage: 24.4+ KB

Class Distribution:
y
True     0.5125
False    0.4875
Name: proportion, dtype: float64

Feature Importance (based on mutual information with target):
                               feature  mutual_info_score
71                  health_status_good           0.325153
70                   health_status_bad           0.317116
8                                  X_2           0.207705
9                                  X_3           0.159861
18                  checking_status_<0           0.104322
..                                 ...                ...
6                       num_dependents           0.000000
12                                 X_6           0.000000
45  personal_status_female div/dep/mar           0.000000
23   credit_history_delayed previously           0.000000
17            checking_status_0<=X<200           0.000000

[72 rows x 2 columns]

Correlation with Target (for numeric features):
                   feature  correlation_with_target
8                      X_2                 0.379576
4                      age                 0.262928
3          residence_since                -0.259594
2   installment_commitment                -0.232587
0                 duration                -0.207027
9                      X_3                 0.164068
13                     X_7                -0.160819
12                     X_6                 0.155404
14                     X_8                 0.152155
11                     X_5                 0.081763
5         existing_credits                 0.054479
6           num_dependents                -0.046294
1            credit_amount                -0.031406
16                    X_10                 0.024366
7                      X_1                 0.011371
10                     X_4                 0.010288
15                     X_9                -0.010288

Top 10 Features by Mutual Information:
                               feature  mutual_info_score
71                  health_status_good           0.325153
70                   health_status_bad           0.317116
8                                  X_2           0.207705
9                                  X_3           0.159861
18                  checking_status_<0           0.104322
37                 savings_status_<100           0.090815
29         purpose_furniture/equipment           0.089213
36          savings_status_500<=X<1000           0.086038
25  credit_history_no credits/all paid           0.085954
42                       employment_<1           0.081016

Top 10 Numeric Features by Correlation with Target:
                   feature  correlation_with_target
8                      X_2                 0.379576
4                      age                 0.262928
3          residence_since                -0.259594
2   installment_commitment                -0.232587
0                 duration                -0.207027
9                      X_3                 0.164068
13                     X_7                -0.160819
12                     X_6                 0.155404
14                     X_8                 0.152155
11                     X_5                 0.081763

Sample of processed training data:
    duration  credit_amount  installment_commitment  residence_since  \
55  0.304553      -0.489953                1.018969         1.101632
88 -0.467553      -0.401267               -0.993809        -1.542284
26 -0.724921      -0.242119                1.018969         1.101632
42  0.304553      -0.741836                1.018969         0.220326
69 -1.411238      -0.512630               -0.993809        -1.542284

         age  existing_credits  num_dependents       X_1       X_2       X_3  \
55  1.782610         -0.617637       -0.399275  0.308410  1.488342 -1.299132
88 -0.622598          1.212399       -0.399275  1.484022  1.284278  1.120042
26  0.580006          1.212399       -0.399275 -0.320564 -0.936405 -0.614967
42 -0.522381          1.212399       -0.399275  1.590166  0.181766  0.261638
69  0.980874          1.212399        2.504541  0.075748  1.015378  0.681672

    ...  job_high qualif/self emp/mgmt  job_skilled  \
55  ...                            0.0          1.0
88  ...                            0.0          0.0
26  ...                            0.0          0.0
42  ...                            0.0          0.0
69  ...                            0.0          0.0

    job_unemp/unskilled non res  job_unskilled resident  own_telephone_none  \
55                          0.0                     0.0                 0.0
88                          1.0                     0.0                 1.0
26                          0.0                     1.0                 1.0
42                          0.0                     1.0                 1.0
69                          0.0                     1.0                 1.0

    own_telephone_yes  foreign_worker_no  foreign_worker_yes  \
55                1.0                0.0                 1.0
88                0.0                0.0                 1.0
26                0.0                1.0                 0.0
42                0.0                0.0                 1.0
69                0.0                0.0                 1.0

    health_status_bad  health_status_good
55                0.0                 1.0
88                1.0                 0.0
26                0.0                 1.0
42                0.0                 1.0
69                0.0                 1.0

[5 rows x 72 columns]